language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: false
      mono: latest
      dotnet: 2.0.0
    - os: osx # OSX 10.12
      osx_image: xcode9.1
      dotnet: 2.0.0
      dist: trusty
      mono: latest
      sudo: false

script: 
  - dotnet --info
  - ./build.sh All

branches:
  except:
    - gh-pages